services:
    desing_patterns.command.singleton:
        class: App\Command\Singleton
        tags:
          - { name: 'console.command', command: 'training:singleton' }

    design_patterns.command.factory_method:
        class: App\Command\FactoryMethod
        tags:
          - { name: 'console.command', command: 'training:factory_method' }

    desing_patterns.command.abstract_factory:
        class: App\Command\AbstractFactory
        tags:
          - { name: 'console.command', command: 'training:abstract_factory' }